Display businesses poc
encointer/bazaar-web pull request #1
Opened 2021-09-30 05:53 UTC by anizeani

major pr:
basic functionality to display businesses and offerings per community (with icons per business and offering)

2021-10-01 12:50 UTC, brenzi requested changes
Please only use bazaar, not bazar

I need instructions, as in my case it doesn't show anything. I can select the community among the ones I created on my local node, but it doesn't show offerings or businesses
Please provide a README.md in the root with detailed instructions how to build and launch and how to set up the environment with bot-communities

2021-10-01 12:54 UTC, anizeani commented
Sure, I'll do that. You need to run the script: register-businesses.py
before you view it, cause no offerings/businesses are yet created

brenzi ***@***.***> schrieb am Fr., 1. Okt. 2021, 14:50:

> ***@***.**** requested changes on this pull request.
>
> Please only use bazaar, not bazar
>
> I need instructions, as in my case it doesn't show anything. I can select
> the community among the ones I created on my local node, but it doesn't
> show offerings or businesses
> Please provide a README.md in the root with detailed instructions how to
> build and launch and how to set up the environment with bot-communities
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/encointer/bazaar-web/pull/1#pullrequestreview-768918010>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIU6J5O2NLWKTLTPAAVXRATUEWVATANCNFSM5FBPKUXA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-02 07:02 UTC, anizeani commented
> Please only use bazaar, not bazar
Where do you see bazar?
 
> I need instructions, as in my case it doesn't show anything. I can select the community among the ones I created on my local node, but it doesn't show offerings or businesses Please provide a README.md in the root with detailed instructions how to build and launch and how to set up the environment with bot-communities

2021-10-02 15:39 UTC, brenzi approved these changes
I like it. pretty lean solution with minimal dependencies. and its typescript, nice.

I have quite a few style remarks, but lets merge this first and take it from there

2021-10-02 15:39 UTC, merged